version: "3"
services:
  mongodb:
    image: mongo
    container_name: "mongodb"
    ports:
      - 27017:27017
    command: --smallfiles
  app:
    build: .
    ports:
      - 8080:8080
    links:
      - mongodb