version: "3"
services:
  db:
    image: mongo
    container_name: "mongodb"
    ports:
      - 27017:27017
  app:
    build: .
    ports:
      - 8080:8080
    environment:
      MONGO_URL: db
    links:
      - mongodb